packages:
  - apps/*
  - packages/*

catalog:
  "@libsql/client": 0.17.0
  "@types/node": 25.3.0
  "@vitest/browser-playwright": 4.0.18
  drizzle-orm: 0.45.1
  playwright: 1.58.2
  typescript: 5.9.3
  vitest: 4.0.18

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - workerd
