name: Auth State Cache
description: Cache Playwright auth state to skip login

inputs:
  mode:
    description: "restore or save"
    required: true
  enabled:
    description: "Whether caching is enabled (set to vars.CACHE_AUTH_STATE)"
    required: false
    default: "false"

outputs:
  cache-hit:
    description: "Whether there was a cache hit"
    value: ${{ steps.restore.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Restore auth state
      if: inputs.mode == 'restore' && inputs.enabled == 'true'
      id: restore
      uses: actions/cache/restore@v5
      with:
        path: data/auth-state.json
        key: auth-state-${{ github.run_id }}
        restore-keys: |
          auth-state-

    - name: Save auth state
      if: inputs.mode == 'save' && inputs.enabled == 'true'
      uses: actions/cache/save@v5
      with:
        path: data/auth-state.json
        key: auth-state-${{ github.run_id }}
