import type { Pick } from "./shared";

export interface TxTemplate {
  category: string;
  subCategory: string;
  description: string;
  type: "income" | "expense" | "transfer";
  minAmount: number;
  maxAmount: number;
  accountName: string;
  frequency: "monthly" | "biweekly" | "weekly" | "random";
  occurrences?: number;
  fixedDay?: number;
  isTransfer?: boolean;
  transferTarget?: string;
  isExcludedFromCalculation?: boolean;
  /** 特定の月のみ生成する (1-12)。未指定=毎月 */
  onlyMonths?: number[];
}

export const txTemplates: TxTemplate[] = [
  {
    category: "収入",
    subCategory: "給与",
    description: "給与振込",
    type: "income",
    minAmount: 265000,
    maxAmount: 295000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 25,
  },
  {
    category: "収入",
    subCategory: "一時所得",
    description: "夏季賞与",
    type: "income",
    minAmount: 320000,
    maxAmount: 360000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 10,
  },
  {
    category: "収入",
    subCategory: "一時所得",
    description: "冬季賞与",
    type: "income",
    minAmount: 450000,
    maxAmount: 500000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 10,
  },
  {
    category: "収入",
    subCategory: "利息",
    description: "普通預金利息",
    type: "income",
    minAmount: 5,
    maxAmount: 20,
    accountName: "楽天銀行",
    frequency: "monthly",
    fixedDay: 1,
  },
  {
    category: "収入",
    subCategory: "ポイント・割引",
    description: "楽天ポイント付与",
    type: "income",
    minAmount: 500,
    maxAmount: 2000,
    accountName: "楽天ポイント",
    frequency: "monthly",
    fixedDay: 15,
  },
  {
    category: "住宅",
    subCategory: "家賃・地代",
    description: "家賃",
    type: "expense",
    minAmount: 75000,
    maxAmount: 75000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 27,
  },
  {
    category: "その他",
    subCategory: "カード支払い",
    description: "デビットカード支払い",
    type: "expense",
    minAmount: 15000,
    maxAmount: 15000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 26,
  },
  {
    category: "住宅",
    subCategory: "ローン返済",
    description: "ローン返済",
    type: "expense",
    minAmount: 20000,
    maxAmount: 20000,
    accountName: "楽天銀行",
    frequency: "monthly",
    fixedDay: 28,
  },
  ...[3, 4, 5, 6, 10, 11].map((mo): TxTemplate => ({
    category: "水道・光熱費",
    subCategory: "電気代",
    description: "東京電力 電気代",
    type: "expense",
    minAmount: 3500,
    maxAmount: 5500,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 8,
    onlyMonths: [mo],
  })),
  ...[7, 8, 9].map((mo): TxTemplate => ({
    category: "水道・光熱費",
    subCategory: "電気代",
    description: "東京電力 電気代",
    type: "expense",
    minAmount: 8000,
    maxAmount: 12000,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 8,
    onlyMonths: [mo],
  })),
  ...[12, 1, 2].map((mo): TxTemplate => ({
    category: "水道・光熱費",
    subCategory: "電気代",
    description: "東京電力 電気代",
    type: "expense",
    minAmount: 7000,
    maxAmount: 10000,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 8,
    onlyMonths: [mo],
  })),
  ...[4, 5, 6, 7, 8, 9, 10, 11].map((mo): TxTemplate => ({
    category: "水道・光熱費",
    subCategory: "ガス・灯油代",
    description: "東京ガス ガス代",
    type: "expense",
    minAmount: 2000,
    maxAmount: 3500,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 10,
    onlyMonths: [mo],
  })),
  ...[12, 1, 2, 3].map((mo): TxTemplate => ({
    category: "水道・光熱費",
    subCategory: "ガス・灯油代",
    description: "東京ガス ガス代",
    type: "expense",
    minAmount: 5000,
    maxAmount: 8000,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 10,
    onlyMonths: [mo],
  })),
  {
    category: "水道・光熱費",
    subCategory: "水道代",
    description: "水道代",
    type: "expense",
    minAmount: 2000,
    maxAmount: 3500,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 15,
  },
  {
    category: "通信費",
    subCategory: "携帯電話",
    description: "ahamo 月額料金",
    type: "expense",
    minAmount: 2970,
    maxAmount: 2970,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 3,
  },
  {
    category: "通信費",
    subCategory: "インターネット",
    description: "NURO光 月額料金",
    type: "expense",
    minAmount: 5200,
    maxAmount: 5200,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 5,
  },
  {
    category: "食費",
    subCategory: "食料品",
    description: "",
    type: "expense",
    minAmount: 800,
    maxAmount: 4500,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 12,
  },
  {
    category: "食費",
    subCategory: "外食",
    description: "",
    type: "expense",
    minAmount: 800,
    maxAmount: 3000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 6,
  },
  {
    category: "食費",
    subCategory: "カフェ",
    description: "",
    type: "expense",
    minAmount: 300,
    maxAmount: 800,
    accountName: "Suica",
    frequency: "random",
    occurrences: 8,
  },
  {
    category: "日用品",
    subCategory: "日用品",
    description: "",
    type: "expense",
    minAmount: 300,
    maxAmount: 3000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 4,
  },
  {
    category: "日用品",
    subCategory: "ドラッグストア",
    description: "",
    type: "expense",
    minAmount: 500,
    maxAmount: 2500,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 2,
  },
  {
    category: "趣味・娯楽",
    subCategory: "本",
    description: "",
    type: "expense",
    minAmount: 800,
    maxAmount: 2500,
    accountName: "Amazon.co.jp",
    frequency: "random",
    occurrences: 2,
  },
  {
    category: "趣味・娯楽",
    subCategory: "映画・音楽・ゲーム",
    description: "",
    type: "expense",
    minAmount: 500,
    maxAmount: 2000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 2,
  },
  {
    category: "趣味・娯楽",
    subCategory: "スポーツ",
    description: "",
    type: "expense",
    minAmount: 1000,
    maxAmount: 5000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
  },
  {
    category: "衣服・美容",
    subCategory: "衣服",
    description: "",
    type: "expense",
    minAmount: 3000,
    maxAmount: 15000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 1,
  },
  {
    category: "衣服・美容",
    subCategory: "美容院・理髪",
    description: "美容院",
    type: "expense",
    minAmount: 4000,
    maxAmount: 5000,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 20,
  },
  {
    category: "交通費",
    subCategory: "電車",
    description: "",
    type: "expense",
    minAmount: 200,
    maxAmount: 500,
    accountName: "Suica",
    frequency: "random",
    occurrences: 8,
  },
  {
    category: "健康・医療",
    subCategory: "フィットネス",
    description: "ジム月会費",
    type: "expense",
    minAmount: 8000,
    maxAmount: 8000,
    accountName: "三井住友カード(NL)",
    frequency: "monthly",
    fixedDay: 1,
  },
  {
    category: "健康・医療",
    subCategory: "医療費",
    description: "",
    type: "expense",
    minAmount: 1500,
    maxAmount: 5000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
  },
  {
    category: "交際費",
    subCategory: "交際費",
    description: "",
    type: "expense",
    minAmount: 3000,
    maxAmount: 8000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 2,
  },
  {
    category: "教養・教育",
    subCategory: "書籍",
    description: "",
    type: "expense",
    minAmount: 1000,
    maxAmount: 3000,
    accountName: "Amazon.co.jp",
    frequency: "random",
    occurrences: 1,
  },
  {
    category: "税・社会保障",
    subCategory: "所得税・住民税",
    description: "住民税",
    type: "expense",
    minAmount: 15000,
    maxAmount: 15000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 30,
  },
  {
    category: "その他",
    subCategory: "雑費",
    description: "",
    type: "expense",
    minAmount: 200,
    maxAmount: 2000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 2,
  },
  {
    category: "趣味・娯楽",
    subCategory: "旅行",
    description: "GW 旅行 宿泊費",
    type: "expense",
    minAmount: 35000,
    maxAmount: 50000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [5],
  },
  {
    category: "交通費",
    subCategory: "電車",
    description: "新幹線 往復",
    type: "expense",
    minAmount: 20000,
    maxAmount: 28000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [5],
  },
  {
    category: "趣味・娯楽",
    subCategory: "旅行",
    description: "夏休み旅行 宿泊費",
    type: "expense",
    minAmount: 40000,
    maxAmount: 65000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [8],
  },
  {
    category: "趣味・娯楽",
    subCategory: "旅行",
    description: "夏休み旅行 食事・観光",
    type: "expense",
    minAmount: 15000,
    maxAmount: 25000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [8],
  },
  {
    category: "特別な支出",
    subCategory: "家具・家電",
    description: "電子レンジ 買い替え",
    type: "expense",
    minAmount: 25000,
    maxAmount: 35000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [4],
  },
  {
    category: "交際費",
    subCategory: "プレゼント代",
    description: "クリスマスプレゼント",
    type: "expense",
    minAmount: 10000,
    maxAmount: 20000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [12],
  },
  {
    category: "交際費",
    subCategory: "交際費",
    description: "忘年会",
    type: "expense",
    minAmount: 5000,
    maxAmount: 8000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 2,
    onlyMonths: [12],
  },
  {
    category: "税・社会保障",
    subCategory: "その他税・社会保障",
    description: "ふるさと納税",
    type: "expense",
    minAmount: 30000,
    maxAmount: 50000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [11],
  },
  {
    category: "衣服・美容",
    subCategory: "衣服",
    description: "季節の衣類",
    type: "expense",
    minAmount: 8000,
    maxAmount: 20000,
    accountName: "楽天カード",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [3, 10],
  },
  {
    category: "健康・医療",
    subCategory: "医療費",
    description: "健康診断 自己負担",
    type: "expense",
    minAmount: 5000,
    maxAmount: 8000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [6],
  },
  {
    category: "健康・医療",
    subCategory: "医療費",
    description: "歯科定期検診",
    type: "expense",
    minAmount: 3000,
    maxAmount: 6000,
    accountName: "三井住友カード(NL)",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [3, 9],
  },
  {
    category: "収入",
    subCategory: "事業・副業",
    description: "副業報酬",
    type: "income",
    minAmount: 20000,
    maxAmount: 50000,
    accountName: "楽天銀行",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [3, 7, 11],
  },
  {
    category: "収入",
    subCategory: "その他入金",
    description: "メルカリ売上",
    type: "income",
    minAmount: 2000,
    maxAmount: 12000,
    accountName: "楽天銀行",
    frequency: "random",
    occurrences: 1,
    onlyMonths: [2, 5, 8, 10],
  },
  {
    category: "",
    subCategory: "",
    description: "貯蓄口座からの補填",
    type: "transfer",
    minAmount: 28000,
    maxAmount: 47000,
    accountName: "ゆうちょ銀行（貯蓄用）",
    frequency: "monthly",
    fixedDay: 28,
    isTransfer: true,
    transferTarget: "三井住友銀行",
    isExcludedFromCalculation: true,
  },
  {
    category: "",
    subCategory: "",
    description: "三井住友銀行へ振替",
    type: "transfer",
    minAmount: 150000,
    maxAmount: 150000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 26,
    isTransfer: true,
    transferTarget: "楽天銀行",
    isExcludedFromCalculation: true,
  },
  {
    category: "",
    subCategory: "",
    description: "SBI証券へ入金",
    type: "transfer",
    minAmount: 33333,
    maxAmount: 33333,
    accountName: "住信SBIネット銀行",
    frequency: "monthly",
    fixedDay: 1,
    isTransfer: true,
    transferTarget: "SBI証券",
    isExcludedFromCalculation: true,
  },
  {
    category: "",
    subCategory: "",
    description: "Suicaチャージ",
    type: "transfer",
    minAmount: 3000,
    maxAmount: 5000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 10,
    isTransfer: true,
    transferTarget: "Suica",
    isExcludedFromCalculation: true,
  },
  {
    category: "",
    subCategory: "",
    description: "カード引き落とし",
    type: "transfer",
    minAmount: 80000,
    maxAmount: 120000,
    accountName: "三井住友銀行",
    frequency: "monthly",
    fixedDay: 26,
    isTransfer: true,
    transferTarget: "三井住友カード(NL)",
    isExcludedFromCalculation: true,
  },
  {
    category: "",
    subCategory: "",
    description: "カード引き落とし",
    type: "transfer",
    minAmount: 40000,
    maxAmount: 70000,
    accountName: "楽天銀行",
    frequency: "monthly",
    fixedDay: 27,
    isTransfer: true,
    transferTarget: "楽天カード",
    isExcludedFromCalculation: true,
  },
];

const groceryStores = [
  "ライフ",
  "サミット",
  "まいばすけっと",
  "オーケー",
  "イオン",
  "西友",
  "成城石井",
  "業務スーパー",
];
const restaurants = [
  "松屋",
  "すき家",
  "日高屋",
  "サイゼリヤ",
  "ガスト",
  "丸亀製麺",
  "大戸屋",
  "やよい軒",
  "CoCo壱番屋",
  "餃子の王将",
];
const cafes = ["スターバックス", "ドトール", "タリーズ", "コメダ珈琲", "サンマルクカフェ"];
const drugstores = ["マツモトキヨシ", "ウエルシア", "スギ薬局", "ツルハドラッグ"];
const dailyStores = ["ダイソー", "セリア", "無印良品", "ニトリ", "ドン・キホーテ"];
const bookTitles = ["技術書", "新書", "文庫本", "雑誌", "Kindle本"];
const entertainments = ["Netflix", "Spotify", "Steam", "PlayStation Store", "映画館"];
const sports = ["スポーツ用品", "ランニングシューズ", "プロテイン"];
const clothing = ["ユニクロ", "GU", "ZARA", "BEAMS", "UNITED ARROWS", "無印良品"];
const socialEvents = ["飲み会", "送別会", "忘年会", "歓迎会", "同僚とランチ", "友人と食事"];
const medicalDescs = ["歯科", "内科", "皮膚科", "薬局"];
const trainDescs = ["JR東日本", "東京メトロ", "バス"];
const miscDescs = ["コンビニ", "自販機", "クリーニング", "証明写真"];
const educationDescs = ["Udemy", "技術書", "参考書"];

export function getDescription(cat: string, subCat: string, pick: Pick): string {
  if (cat === "食費" && subCat === "食料品") return pick(groceryStores);
  if (cat === "食費" && subCat === "外食") return pick(restaurants);
  if (cat === "食費" && subCat === "カフェ") return pick(cafes);
  if (cat === "日用品" && subCat === "ドラッグストア") return pick(drugstores);
  if (cat === "日用品" && subCat === "日用品") return pick(dailyStores);
  if (cat === "趣味・娯楽" && subCat === "本") return pick(bookTitles);
  if (cat === "趣味・娯楽" && subCat === "映画・音楽・ゲーム") return pick(entertainments);
  if (cat === "趣味・娯楽" && subCat === "スポーツ") return pick(sports);
  if (cat === "衣服・美容" && subCat === "衣服") return pick(clothing);
  if (cat === "交際費") return pick(socialEvents);
  if (cat === "健康・医療" && subCat === "医療費") return pick(medicalDescs);
  if (cat === "交通費") return pick(trainDescs);
  if (cat === "その他") return pick(miscDescs);
  if (cat === "教養・教育") return pick(educationDescs);
  return "";
}

export interface TxRecord {
  mfId: string;
  date: string;
  accountId: number | null;
  accountName: string;
  category: string | null;
  subCategory: string | null;
  description: string | null;
  amount: number;
  type: string;
  isTransfer: boolean;
  isExcludedFromCalculation: boolean;
  transferTarget: string | null;
  transferTargetAccountId: number | null;
}

export type GroupMonthlyData = {
  income: Record<string, number>;
  expense: Record<string, number>;
  catTotals: Record<string, Record<string, { income: number; expense: number }>>;
};
